version: '3.6'

services:
  wp:
    image: wordpress:5.9.3
    ports:
      - 80:80
    volumes:
      - ./config/php.conf.ini/php.ini:/usr/local/etc/php/php.ini
      - ./wordpress:/var/www/html 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_db 
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DEBUG: 1      
    depends_on:
      - db
    links:
      - db
  
  wpcli:
    build: ./docker/wpcli/
    image: wpcli:custom
    container_name: raccoon_boilerplate_wpcli
    volumes:      
      - ./config/php.conf.ini/php.ini:/usr/local/etc/php/php.ini
      - ./wordpress:/var/www/html            
    working_dir: /var/www/html
    environment:    
      WP_CLI_CACHE_DIR: /var/www/html/wpcli/.cache/
      WP_CLI_PACKAGES_DIR: /var/www/html/wpcli/packages
  
  pma:
    image: phpmyadmin/phpmyadmin
    volumes:
      - ./config/php.conf.ini/php.ini:/usr/local/etc/php/php.ini
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 8080:80
    links:
      - db:db

  db:
    image: mysql:latest
    ports:
      - 3306:3306 
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wordpress-db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_ROOT_PASSWORD: admin

volumes:
  db_data:



