FROM wordpress:5.3.2

EXPOSE 80

# Set workdir
WORKDIR /var/www/html

# Copy php uploads config file
COPY ./config/php.conf.ini /usr/local/etc/php/conf.d/

# Copy wordpress content
COPY ./wordpress/wp-content /usr/src/wordpress/wp-content/ 